name: 01 - Trigger basics

on: 
    push:
    pull_request:
    workflow_dispatch:

jobs:
    show_context:
        runs-on: ubuntu-latest
        steps:
            - name: Show basic info
              run: |
                echo "event: $GITHUB_EVENT_NAME"
                echo "ref: $GITHUB_REF"
                echo "sha: $GITHUB_SHA"
                echo "actor: $GITHUB_ACTOR"
              shell: bash

    print_random_number:
        runs-on: ubuntu-latest
        steps:
            - name: random-number-generator
              run: echo $RANDOM
              shell: bash  
        