name: 02 - Checkout + Script

on: workflow_dispatch

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Make executable
        run: chmod +x ./scripts/hello.sh
        shell: bash

      - name: Run script
        run: ./scripts/hello.sh
        shell: bash